# Site
repository: terdong/terdong.github.io
favicon: images/favicon.ico

# Personal info
name: DongHee Kim
title: Full Stack Scala Developer
email: terdong@gmail.com
website: resume.teamgehem.com
Phone: +82-10-3084-0948

# Social links
#twitter_username: facespics
github_username:  terdong
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: terdong
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_donghee.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is DongHee and I am a full stack scala developer. Currently I am developing some open source project and private project. My career as a developer is five years old. Previously, I was a mobile online game client developer. As mentioned above now I would like to develop server backend. I am familiar with Scala, Java, C# and C++ languages and can develop web server, application with Play Frameowrk and Akka. If you want to see the code or demo for my projects, please visit github or demo site(It might not be perfect yet. Also a few are still under development).

  I am most skilled in: <mark>Play Framework</mark> and <mark>Akka</mark>
  
  My overall skills are:
  * High Level Language: Scala, Java, C#, C++
  * Middle Level Language: Shell, JavaScript
  * Game Engine: Unity, Cocos2dx
  * Web tech: Scalajs, HTML5, SCSS
  * Database: Postgresql, MongoDB, Redis
  * Mobile SDK: Android, iOS
  * VCS: Git, Svn
  * OS experience: Windows, Linux(Ubuntu), Mac OS
  * Cloud Server experience: AWS, Heroku, Azure, GCP
  * Tools: Ms Office(Excel, Powerpoint), Photoshop, Cubase
  * IDE: Intellij, Eclipse, Visual Studio, Xcode, Vim
  * Etc: Docker, Traefik

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in developing open source project and researching server side library some of my other hobbies are:
   - Playing video games and guitar
   - Watching Football
   - Walking with my dog
   - Studying English
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
